# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smart_farm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMouseTracking(False)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 750, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(750, 700))
        self.tabWidget.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane{border-radius:20px;margin:9px;}\n"
"QTabBar::tab{color:white;\n"
"background-color:rgba(255,255,255,0.3);\n"
"border-radius:20px;\n"
"width:230px;\n"
"height:90px;\n"
" margin:9px;}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(100, 70))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("background-color:transparent;")
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 731, 440))
        font = QtGui.QFont()
        font.setFamily("휴먼옛체")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setStyleSheet("QTabWidget::tab-bar{alignment: center;}\n"
"QTabBar::tab:selected {color:white;\n"
"background-color:rgb(0,0,0);}\n"
"QTabWidget::pane{border-radius:20px;margin:9px;}\n"
"QTabBar::tab{color:black;\n"
"background-color:rgba(255,255,255,0.3);\n"
"border-radius:20px;\n"
"width:50px;\n"
"height:50px;\n"
" margin:9px;}")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_4.setObjectName("tab_4")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(410, 25, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(410, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_2.setObjectName("label_2")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(50, 185, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(50, 260, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(410, 260, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_4.setObjectName("label_4")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(560, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_15.setObjectName("label_15")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(410, 185, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(50, 25, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(50, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label.setObjectName("label")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(560, 260, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_16.setObjectName("label_16")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(530, 30, 70, 70))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("humi.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(200, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_14.setObjectName("label_14")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(2, 0, 711, 351))
        self.label_9.setStyleSheet("background-color:rgba(0, 0, 0, 0.45); border-radius:30px;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(170, 30, 70, 70))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("temp.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setGeometry(QtCore.QRect(200, 265, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_37.setObjectName("label_37")
        self.label_9.raise_()
        self.label_11.raise_()
        self.label_2.raise_()
        self.label_12.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_15.raise_()
        self.label_10.raise_()
        self.label_13.raise_()
        self.label.raise_()
        self.label_16.raise_()
        self.label_8.raise_()
        self.label_14.raise_()
        self.label_5.raise_()
        self.label_37.raise_()
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(2, 0, 711, 351))
        self.label_18.setStyleSheet("background-color:rgba(0, 0, 0, 0.45); border-radius:30px;")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(410, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(200, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(410, 185, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        self.label_28.setGeometry(QtCore.QRect(560, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(560, 260, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(50, 25, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setGeometry(QtCore.QRect(410, 25, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.tab_5)
        self.label_33.setGeometry(QtCore.QRect(50, 185, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_5)
        self.label_34.setGeometry(QtCore.QRect(50, 260, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_5)
        self.label_35.setGeometry(QtCore.QRect(50, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_5)
        self.label_36.setGeometry(QtCore.QRect(410, 260, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_36.setObjectName("label_36")
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(200, 260, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_32.setObjectName("label_32")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(2, 0, 711, 351))
        self.label_19.setStyleSheet("background-color:rgba(0, 0, 0, 0.45); border-radius:30px;")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_38 = QtWidgets.QLabel(self.tab_6)
        self.label_38.setGeometry(QtCore.QRect(50, 185, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_6)
        self.label_39.setGeometry(QtCore.QRect(50, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_6)
        self.label_40.setGeometry(QtCore.QRect(560, 260, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_6)
        self.label_41.setGeometry(QtCore.QRect(50, 25, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_6)
        self.label_42.setGeometry(QtCore.QRect(410, 25, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab_6)
        self.label_43.setGeometry(QtCore.QRect(410, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_6)
        self.label_44.setGeometry(QtCore.QRect(410, 260, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_6)
        self.label_45.setGeometry(QtCore.QRect(200, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.tab_6)
        self.label_46.setGeometry(QtCore.QRect(200, 260, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_6)
        self.label_47.setGeometry(QtCore.QRect(560, 100, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_6)
        self.label_48.setGeometry(QtCore.QRect(50, 260, 200, 75))
        font = QtGui.QFont()
        font.setFamily("양재참숯체B")
        font.setPointSize(20)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("background-color:rgba(255,255,255);background:transparent;")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_6)
        self.label_49.setGeometry(QtCore.QRect(410, 185, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.tabWidget_2.addTab(self.tab_6, "")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("raspberry-pi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("background-color:transparent;")
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(500, 40, 150, 61))
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("toggle_switch_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("toggle_switch_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(100, 100))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(False)
        self.pushButton.setObjectName("pushButton")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(0, 0, 731, 440))
        self.label_22.setStyleSheet("background-color:rgba(0, 0, 0, 0.45); border-radius:20px;")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(70, 35, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 130, 150, 61))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(70, 125, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 310, 150, 61))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setChecked(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(70, 305, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(70, 215, 200, 75))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(500, 220, 150, 61))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setChecked(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_22.raise_()
        self.pushButton.raise_()
        self.label_24.raise_()
        self.pushButton_2.raise_()
        self.label_25.raise_()
        self.pushButton_3.raise_()
        self.label_27.raise_()
        self.label_26.raise_()
        self.pushButton_4.raise_()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("background-color:transparent;")
        self.tab_3.setObjectName("tab_3")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 731, 440))
        self.label_17.setStyleSheet("background-color:rgba(0, 0, 0, 0.45); border-radius:20px;")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 20, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;\n"
"color:#ff007f;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(200, 20, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;color:#aaff00;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setGeometry(QtCore.QRect(370, 150, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;\n"
"color:#55aaff;")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_14.setGeometry(QtCore.QRect(540, 150, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;\n"
"color:#aaffff;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 150, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;\n"
"color:#ff007f;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_11.setGeometry(QtCore.QRect(370, 20, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;\n"
"color:#ff007f;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(200, 150, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;color:#aaff00;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_12.setGeometry(QtCore.QRect(540, 20, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;color:#aaff00;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 280, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;\n"
"color:#ff007f;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_15.setGeometry(QtCore.QRect(370, 280, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;\n"
"color:#55aaff;")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setGeometry(QtCore.QRect(200, 280, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;color:#aaff00;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_16.setGeometry(QtCore.QRect(540, 280, 160, 100))
        font = QtGui.QFont()
        font.setFamily("휴먼편지체")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("background-color:rgb(220, 150, 120); border-radius:10px;\n"
"color:#aaffff;")
        self.pushButton_16.setObjectName("pushButton_16")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("sensor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon3, "")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(-10, 0, 811, 611))
        self.label_7.setStyleSheet("background-color:rgba(0, 0, 0, 0.45);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("smart_farm.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.label_7.raise_()
        self.tabWidget.raise_()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(2)
        self.pushButton_5.clicked.connect(Dialog.btn_main_to_temp)
        self.pushButton_6.clicked.connect(Dialog.btn_main_to_humi)
        self.pushButton_13.clicked.connect(Dialog.btn_main_to_ph)
        self.pushButton_14.clicked.connect(Dialog.btn_main_to_co2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#aaff00;\">지표 습도</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#55aaff;\">pH</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">%</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#aaffff;\">Co2 농도</span></p></body></html>"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#ff007f;\">지표 온도</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">ppm</span></p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">°C</span></p></body></html>"))
        self.label_37.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">pH</span></p></body></html>"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">°C</span></p></body></html>"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#aaff00;\">외부 습도</span></p></body></html>"))
        self.label_28.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">%</span></p></body></html>"))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">%</span></p></body></html>"))
        self.label_30.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#ff007f;\">내부 온도</span></p></body></html>"))
        self.label_31.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#aaff00;\">내부 습도</span></p></body></html>"))
        self.label_33.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#ff007f;\">외부 온도</span></p></body></html>"))
        self.label_34.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_35.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_36.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_32.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">°C</span></p></body></html>"))
        self.label_38.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#55aaff;\">물 pH</span></p></body></html>"))
        self.label_39.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_40.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">m/s</span></p></body></html>"))
        self.label_41.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#ff007f;\">일조량</span></p></body></html>"))
        self.label_42.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#aaff00;\">강수량</span></p></body></html>"))
        self.label_43.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_44.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_45.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">°C</span></p></body></html>"))
        self.label_46.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">pH</span></p></body></html>"))
        self.label_47.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">mm</span></p></body></html>"))
        self.label_48.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.label_49.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#aaffff;\">풍속</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "General"))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#aaff00;\">개폐기_1</span></p></body></html>"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#aaff00;\">개폐기_2</span></p></body></html>"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#aaffff;;\">환풍기</span></p></body></html>"))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; color:#55aaff;\">펌프</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Control"))
        self.pushButton_5.setText(_translate("Dialog", "온도"))
        self.pushButton_6.setText(_translate("Dialog", "습도"))
        self.pushButton_7.setText(_translate("Dialog", "내부 온도"))
        self.pushButton_8.setText(_translate("Dialog", "내부 습도"))
        self.pushButton_9.setText(_translate("Dialog", "외부 온도"))
        self.pushButton_10.setText(_translate("Dialog", "외부 습도"))
        self.pushButton_11.setText(_translate("Dialog", "일조량"))
        self.pushButton_12.setText(_translate("Dialog", "강수량"))
        self.pushButton_13.setText(_translate("Dialog", "ph"))
        self.pushButton_14.setText(_translate("Dialog", "Co2 농도"))
        self.pushButton_15.setText(_translate("Dialog", "물 ph"))
        self.pushButton_16.setText(_translate("Dialog", "풍속"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Sensor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

